image: node:16

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  stage: deploy
  script:
    - cp -r build/ public/
  artifacts:
    paths:
      - public
  only:
    - main
